import { Bean } from "@/lib/types";

export const sampleBeans: Bean[] = [
  {
    id: "bean-001-uuid",
    name: "Ethiopia Yirgacheffe",
    roaster: "Square Mile",
    roast_date: "2026-01-15",
    weight_grams: 250,
    cost: 16.5,
    flavour_profile: "Floral, Citrus, Bergamot",
    country: "Ethiopia",
    region: "Yirgacheffe",
    variety: "Heirloom",
    processing: "Washed",
    archived: false,
    rest_days: null,
    is_frozen: false,
    notes: null,
    display_order: null,
  },
  {
    id: "bean-002-uuid",
    name: "Colombia Huila",
    roaster: "Tim Wendelboe",
    roast_date: "2026-01-20",
    weight_grams: 250,
    cost: 18.0,
    flavour_profile: "Caramel, Red Apple, Chocolate",
    country: "Colombia",
    region: "Huila",
    variety: "Caturra",
    processing: "Washed",
    archived: false,
    rest_days: 21,
    is_frozen: false,
    notes: null,
    display_order: null,
  },
  {
    id: "bean-003-uuid",
    name: "Kenya Othaya",
    roaster: "Square Mile",
    roast_date: "2026-02-01",
    weight_grams: 350,
    cost: 19.0,
    flavour_profile: "Blackcurrant, Tomato, Bright",
    country: "Kenya",
    region: "Nyeri",
    variety: "SL28",
    processing: "Washed",
    archived: false,
    rest_days: null,
    is_frozen: false,
    notes: null,
    display_order: 1,
  },
  {
    id: "bean-004-uuid",
    name: "Guatemala Antigua",
    roaster: "La Cabra",
    roast_date: null, // Invalid date case
    weight_grams: 250,
    cost: 15.0,
    flavour_profile: "Chocolate, Nuts",
    country: "Guatemala",
    region: "Antigua",
    variety: "Bourbon",
    processing: "Washed",
    archived: false,
    rest_days: null,
    is_frozen: false,
    notes: null,
    display_order: null,
  },
  {
    id: "bean-005-uuid",
    name: "Panama Geisha",
    roaster: "Tim Wendelboe",
    roast_date: "2025-12-10",
    weight_grams: 100,
    cost: 45.0,
    flavour_profile: "Jasmine, Peach, Tea-like",
    country: "Panama",
    region: "Boquete",
    variety: "Geisha",
    processing: "Washed",
    archived: false,
    rest_days: 14,
    is_frozen: true,
    notes: "Frozen on 2025-12-15",
    display_order: null,
  },
  {
    id: "bean-006-uuid",
    name: "Old Brazil Santos",
    roaster: "Local Roaster",
    roast_date: "2025-06-01",
    weight_grams: 250,
    cost: 10.0,
    flavour_profile: "Nuts, Chocolate",
    country: "Brazil",
    region: "Santos",
    variety: "Mundo Novo",
    processing: "Natural",
    archived: true,
    rest_days: null,
    is_frozen: false,
    notes: null,
    display_order: null,
  },
];
